### ISSUE TITLE
Add built in option for less support

### ISSUE THREAD

**Issue by swashata** [swashata/wp-webpack-script#469]
Many popular libraries like antd, elemental ui uses `less`. So we should have it built in. Right now, once can do it like

```js
const webpackConfigWithLess = (config, merge, appDir, isDev) => {
	const configWithLess = {
		module: {
			rules: [
				{
					test: /\.less$/,
					use: [
						isDev
							? 'style-loader'
							: {
									loader: MiniCssExtractPlugin.loader,
									options: {
										sourceMap: true,
									},
							  },
						{
							loader: 'css-loader',
							options: {
								importLoaders: 1,
								sourceMap: true,
							},
						},
						{
							loader: 'postcss-loader',
							options: {
								sourceMap: true,
							},
						},
						{
							loader: 'less-loader',
							options: {
								sourceMap: true,
							},
						},
					],
				},
			],
		},
	};

	return merge(config, configWithLess);
};
```

## Tasks

- [x] Add prompt `Does your project require less`.
- [x] Add `hasLess` in project config, defaulting to `undefined` which would behave as `false`.
- [x] Add `less-loader` in project.
- [x] Add `less` in devDependencies of the user if `hasLess`.
- [x] Add `less-loader` if needed.
- [x] Turn on `inlineJs` of `less-loader` because `antd` needs it that way.
