### ISSUE TITLE
Version 5 RoadMap

### ISSUE THREAD

**Issue by swashata** [swashata/wp-webpack-script#977]
## 🗳️ NEW FEATURES

- [x] When doing `yarn start` prompt for doing a single webpack build or doing multi as before.
- [x] Add built-in support for react-refresh.
- [x] Show entry name during typecheck.
- [x] See if airbnb eslint config can be enabled for ESLint 7.
- [x] Add support for latest fork-ts-checker-webpack-plugin.

## 🐛 BUG FIXES

- [x] See why build is failing.
- [x] Update dependencies.

## ↩️ PULL REQUESTS

- [x] #971 `themeType` documentation.

**Comment by swashata** [comment]
I could not use inquirer for prompting because it killed the console input totally.

**Comment by swashata** [comment]
Let's not get hung up on storybook at the moment. I need to do more research.
